name: flutter_gen_builder
description: Custom build_runner builder for creating synthetic flutter_gen package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  build: ^2.3.0
  path: ^1.9.0
  yaml: ^3.1.3
